service: baliraja
frameworkVersion: '4'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  memorySize: 128


functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*' 